version: '3.1'

services:
  eureka_server:
    image: 'kopsoyleydi/transaction_eureka_server'
    container_name: 'transaction_eureka_server'
    ports:
      - 8761:8761
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
  api-gateway:
    image: 'kopsoyleydi/transaction-api-gateway'
    container_name: 'transaction_api_gateway'
    ports:
      - 9000:9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  transaction_service:
    image: 'kopsoyleydi/transaction_back_service'
    container_name: 'transaction_service'
    ports:
      - 9002:9002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  client_service:
    image: 'kopsoyleydi/transaction_client_service'
    container_name: 'transaction_client_server'
    environment:
      - SERVER_PORT=9001
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:2345/app
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_SHOW_SQL=true
      - LIQUIBASE_CHANGELOG=classpath:/db/changelog/db.changelog-master.xml # Liquibase changelog file
    volumes:
      - ./db/changelog:/liquibase/changelog # Mount Liquibase changelog file
      - ./db/data:/liquibase/data # Mount Liquibase data files
    ports:
      - 9001:9001
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9001/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
